name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Deply to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "simple-weather-app-test-2022" #Must be unique in Heroku
          heroku_email: "a.nazari5868@gmail.com"
          usedocker: true
          env_file: .env
